source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ASDIOUSB_Example', :exclusive => true do
  pod "ASDIOUSB", :path => "../"
end

target 'ASDIOUSB_Tests', :exclusive => true do
  pod "ASDIOUSB", :path => "../"

  pod 'Kiwi'
end
